(function() {var implementors = {};
implementors["tokio_proto"] = ["impl&lt;S,&nbsp;T,&nbsp;E&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/trait.Future.html' title='futures::Future'>Future</a> for <a class='struct' href='tokio_proto/multiplex/struct.Multiplex.html' title='tokio_proto::multiplex::Multiplex'>Multiplex</a>&lt;S,&nbsp;T&gt; <span class='where'>where T: <a class='trait' href='tokio_proto/multiplex/trait.Transport.html' title='tokio_proto::multiplex::Transport'>Transport</a>&lt;Error=E&gt;, S: <a class='trait' href='tokio_proto/multiplex/trait.Dispatch.html' title='tokio_proto::multiplex::Dispatch'>Dispatch</a>&lt;InMsg=T::In,&nbsp;InBody=T::BodyIn,&nbsp;OutMsg=T::Out,&nbsp;Error=E&gt;, E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='tokio_proto/enum.Error.html' title='tokio_proto::Error'>Error</a>&lt;E&gt;&gt;</span>","impl&lt;T,&nbsp;S,&nbsp;E&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/trait.Future.html' title='futures::Future'>Future</a> for <a class='struct' href='tokio_proto/multiplex/struct.Server.html' title='tokio_proto::multiplex::Server'>Server</a>&lt;S,&nbsp;T&gt; <span class='where'>where T: <a class='trait' href='tokio_proto/multiplex/trait.Transport.html' title='tokio_proto::multiplex::Transport'>Transport</a>&lt;Error=E&gt;, S: <a class='trait' href='tokio_proto/multiplex/trait.ServerService.html' title='tokio_proto::multiplex::ServerService'>ServerService</a>&lt;Request=T::Out,&nbsp;Response=T::In,&nbsp;Body=T::BodyIn,&nbsp;Error=E&gt;, E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='tokio_proto/enum.Error.html' title='tokio_proto::Error'>Error</a>&lt;E&gt;&gt;</span>","impl&lt;T,&nbsp;S,&nbsp;E&gt; <a class='trait' href='https://docs.rs/futures/0.1/futures/trait.Future.html' title='futures::Future'>Future</a> for <a class='struct' href='tokio_proto/pipeline/struct.Server.html' title='tokio_proto::pipeline::Server'>Server</a>&lt;S,&nbsp;T&gt; <span class='where'>where T: <a class='trait' href='tokio_proto/pipeline/trait.Transport.html' title='tokio_proto::pipeline::Transport'>Transport</a>&lt;Error=E&gt;, S: <a class='trait' href='tokio_proto/pipeline/trait.ServerService.html' title='tokio_proto::pipeline::ServerService'>ServerService</a>&lt;Request=T::Out,&nbsp;Response=T::In,&nbsp;Body=T::BodyIn,&nbsp;Error=E&gt;, E: <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.From.html' title='core::convert::From'>From</a>&lt;<a class='enum' href='tokio_proto/enum.Error.html' title='tokio_proto::Error'>Error</a>&lt;E&gt;&gt;</span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
